configfile: '../config/config.yaml'

#include: 'rules/01parse.smk' 
include: 'rules/02scanpy.smk'
#include: 'rules/03scanpy_testing.smk'
#include: 'rules/04pegasus.smk'
#include: 'rules/04qtl.smk'


# Set QTL tool
QTL_TOOL = config["eQTL"]["tool"]
qtl_files = []

if QTL_TOOL == "fastqtl":
    for chunk in range(config["eQTL"]["num_chunks"]):
        qtl_files.append(config["output_files"]["fastqtl_output"].format(chunk=chunk))
        qtl_files.append(config["output_files"]["fastqtl_perm_output"].format(chunk=chunk)) 

elif QTL_TOOL == "tensorqtl":
    qtl_files.append(config["output_files"]["tensorqtl_output"])
    qtl_files.append(config["output_files"]["tensorqtl_perm_output"])    

rule all:
    input:
#        "../resources/refs/ref.done",
#        #expand("../resources/fqs/{sample}", sample=samples) 
#        expand("../resources/fqs/concat/{sample_id}_R{read}.fastq.gz", sample_id = config['samples'], read = [1,2]),
#        expand("../results/{sample_id}/run.done", sample_id = config['samples']) 
#        expand("../results/01MRGD_fqs/{sample}_R{read}.fastq.gz", sample = ALL_SAMPLES, read = [1,2])
#        expand("../results/02PARSE/{sample}/run.done", sample = ALL_SAMPLES)
#         "../results/02PARSE/combine_plate1/run.done"
#         expand("../results/03SCANPY/testing_runs/scanpy_qc_testing_{plate}.html", plate = config['plate'])
#         expand("../results/03SCANPY/scanpy_qc_{plate}.html", plate = config['plate']),
#         "../results/03SCANPY/scanpy_clustering.html"
#          "../results/03SCANPY/scanpy_annotation.html",
          "../results/03SCANPY/scanpy_cell_label_and_pseudobulk.html"
#          expand("../results/04PEGASUS/pegasus_qc_{plate}.html", plate = config['plate']) 
#           expand("../results/04FASTQTL/fastQTL_{chunk}_txt.gz", chunk = range(1, 101)),
#           expand("../results/04FASTQTL/permutations_{chunk}_txt.gz", chunk = range(1, 101)),
#        qtl_files
