configfile: '../config/config.yaml'

#include: 'rules/01parse.smk' 
#include: 'rules/02scanpy.smk'
#include: 'rules/03genotypes_pre_impute'
#include: 'rules/04pegasus.smk'
include: 'rules/04qtl.smk'
#include: 'rules/04genotypes.smk'

# Set QTL tool
QTL_TOOL = config["eQTL"]["tool"]
CELL_TYPES = config["cell_types"]
CHROMOSOMES = list(range(1, 23)) + ["X"]

qtl_files = []

if QTL_TOOL == "fastqtl":
    for chunk in range(config["eQTL"]["num_chunks"]):
        qtl_files.append(config["output_files"]["fastqtl_output"].format(chunk=chunk))
        qtl_files.append(config["output_files"]["fastqtl_perm_output"].format(chunk=chunk)) 

elif QTL_TOOL == "tensorqtl":
    for cell_type in config["cell_types"]:
        qtl_files.append(config["output_files"]["tensorqtl_output"].format(cell_type=cell_type))
        qtl_files.append(config["output_files"]["tensorqtl_perm_output"].format(cell_type=cell_type))    
        qtl_files.append(config["output_files"]["tensorqtl_cat_log_output"].format(cell_type=cell_type))

# Rule all with optional plot_qtl inclusion
qtl_plots = ["../results/04TENSORQTL/plots/plot_qtl.done"] if config["plot_qtl"]["run"] else []

rule all:
    input:
#        "../resources/refs/ref.done",
#        #expand("../resources/fqs/{sample}", sample=samples) 
#        expand("../resources/fqs/concat/{sample_id}_R{read}.fastq.gz", sample_id = config['samples'], read = [1,2]),
#        expand("../results/{sample_id}/run.done", sample_id = config['samples']) 
#        expand("../results/01MRGD_fqs/{sample}_R{read}.fastq.gz", sample = ALL_SAMPLES, read = [1,2])
#        expand("../results/02PARSE/{sample}/run.done", sample = ALL_SAMPLES)
#         "../results/02PARSE/combine_plate1/run.done"
#         expand("../results/03SCANPY/testing_runs/scanpy_qc_testing_{plate}.html", plate = config['plate'])
#         expand("../results/03SCANPY/scanpy_qc_{plate}.html", plate = config['plate']),
#         "../results/04GENOTYPES/GenotypeQCtoHRC/eqtl_genotypes_hg19.bed"
#         "../results/04GENOTYPES/GenotypeQCtoHRC/eqtlgenotypeshg38pretm.qc_report.html"
#       "../results/03SCANPY/scanpy_clustering.html",
#       "../results/03SCANPY/scanpy_annotation.html",
#        "../results/03SCANPY/scanpy_extra.html",
#        "../results/03SCANPY/scanpy_cell_label_and_pseudobulk.html",
#          expand("../results/04PEGASUS/pegasus_qc_{plate}.html", plate = config['plate']) 
        qtl_files,
#        qtl_plots,
#        "../results/04GENOTYPES/TOPMED/impute_check/chr_ALL_summary.tsv",
#        "../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt.vcf.gz.tbi",
#        "../results/04GENOTYPES/TOPMED/filtered/combined_genotype_processing.log", 
#        "../results/04GENOTYPES/TOPMED/filtered/geno_sample_list.txt",
#        "../results/04GENOTYPES/TOPMED/covariates/pca.eigenvec"
