---
title: "Genotyping QC pre-Imputation"
author: "Darren Cameron"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  in_dir: null
---

```{r setup, include=FALSE, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(stringr)
library(DT)
in_dir <- params$in_dir
```

## QC steps

1.
2. 
3. 
4. 
5. 
6. 
7.
8.
9.
10.

***

## QC tables {.tabset}

***

### QC 3: Sex ambiguity

***

```{r sex_summary, results='asis', echo=FALSE}
sex_data <- system(
  paste0("cat ", in_dir, "eqtl_genotypes_hg19.qc3.sexcheck"),
  intern = TRUE
)

temp_file <- tempfile(fileext = ".txt")
writeLines(sex_data, temp_file)

sex_tbl <- read.table(
  file = temp_file,
  header = FALSE,  # Header is included in sex_data
  skip = 1,        # Skip the header row
  col.names = c("FID", "IID", "PEDSEX", "SNPSEX", "STATUS", "F", "YCOUNT"),
  colClasses = c("character", "character", "integer", "integer", "character", "numeric", "integer"),
  sep = ""  # Let read.table auto-detect whitespace (spaces or tabs)
) %>%
  as_tibble()  # Convert to tibble for consistency

file.remove(temp_file)

datatable(sex_tbl, caption = 'Table 1. Sex ambiguities')
```

***

### QC 4: Kinship 

+ Note: 

***

```{r kinship_summary, results='asis', echo=FALSE}
kinship_data <- system(
  paste0("cat ", in_dir, "eqtl_genotypes_hg19.qc4.pcrelate.kin"),
  intern = TRUE
)

kinship_tbl <- read_tsv(file = I(kinship_data), col_types = cols())

datatable(kinship_tbl, caption = 'Table 2. Related samples') 
```

***

### QC 5: Ancestry {.tabset}

***

#### All

```{r ancestry_summary, results='asis', echo=FALSE}
ancestry_data <- system(
  paste0("cat ", in_dir, "eqtl_genotypes_hg19.qc5.ancestry_inference.txt | cut -f 1-9"),
  intern = TRUE
)

ancestry_tbl <- read_tsv(file = I(ancestry_data), col_types = cols())

datatable(ancestry_tbl, caption = 'Table 3. Ancestry prediction per sample') 
```

***

#### Non_European

```{r ancestry_nonEur_summary, results='asis', echo=FALSE}
ancestry_nonEur_tbl <- ancestry_tbl |>
  filter(biogeographic_prediction != 'European')

datatable(ancestry_nonEur_tbl, caption = 'Table 4. Ancestry (non European) prediction per sample') 
```

**Non-European sample IDs**: `r ancestry_tbl |> filter(biogeographic_prediction != 'European') |> pull(FID)`

***

### QC 6: Post-GenotypeQCtoHRC checks 

+ Still to add counts of SNP removals from post-check logs

***

```{r, snp counts}
pre_snp_cnts_tbl <- read_tsv(paste0(in_dir, 'final_vcf_chr_counts.tsv'), col_names = c('chr', 'gQCtoHRC_cnts'))
post_snp_cnts_tbl <- read_tsv(paste0(in_dir, 'gQC2hrc_vcf_chr_counts.tsv'), col_names = c('chr', 'final_cnts'))
final_snp_cnt_tbl <- pre_snp_cnts_tbl |>
  left_join(post_snp_cnts_tbl)
datatable(final_snp_cnt_tbl, caption = 'Table 5. SNP counts after GenotypeQCtoHRC and post-SNP checks') 
```