# --------------------------------------------------------------------------------------
#
#    pseudotime_pseudobulk.py
#
#    Pseudotime quantile binning and pseudobulk generation for a single
#    neurogenic trajectory of the prenatal human cerebral cortex snRNA-seq atlas.
#
#    Pipeline:
#      1. Load trajectory-specific pseudotime h5ad
#      2. Load genotype sample list and identify overlapping samples
#      3. Restore raw counts from layers['counts'] into adata.X
#      4. Assign equal-cell-number quantile bins for Q4, Q5, Q6
#      5. Generate five-panel QC figure (cell type, pseudotime, Q4, Q5, Q6 bins)
#      6. Generate pseudobulk CSVs per bin per Q value
#      7. Write per-bin summary CSV
#      8. Write sentinel file
#
#    Pseudobulk format: samples as rows, genes as columns.
#    Raw integer counts are summed across cells per sample per bin.
#
#    Memory management: subsets are deleted and gc.collect() called after
#    each bin to avoid holding multiple large objects simultaneously.
#
#    Usage: called via Snakemake rule pseudobulk_trajectory
#
# --------------------------------------------------------------------------------------

import sys
import gc
import logging
import warnings
import numpy as np
import pandas as pd
import scipy.sparse as sp
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import scanpy as sc
import anndata as ad

from pathlib import Path
from datetime import datetime
from scanpy_gene_lists import custom_palette

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

RANDOM_SEED  = 1234
Q_VALUES     = [4, 5, 6]

# ── Logging ───────────────────────────────────────────────────────────────────

log_file = snakemake.log[0]
logging.basicConfig(
    filename=log_file,
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger()
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.INFO)
logger.addHandler(handler)

sc.settings.verbosity = 1

# ── Parameters ────────────────────────────────────────────────────────────────

input_h5ad       = str(snakemake.input.h5ad)
geno_sample_file = str(snakemake.input.geno)
sentinel_file    = str(snakemake.output.sentinel)
output_dir       = Path(sentinel_file).parent

logger.info(f"Input h5ad:        {input_h5ad}")
logger.info(f"Geno sample file:  {geno_sample_file}")
logger.info(f"Output directory:  {output_dir}")

output_figure  = str(output_dir / "pseudobulk_qc.png")
output_summary = str(output_dir / "pseudobulk_summary.csv")

# ── 1. Load data ──────────────────────────────────────────────────────────────

logger.info(f"Loading pseudotime adata from: {input_h5ad}")
adata = ad.read_h5ad(input_h5ad)
logger.info(f"Loaded: {adata.shape[0]:,} cells x {adata.shape[1]:,} genes")

# Read trajectory metadata
traj       = adata.uns['trajectory']
trajectory = traj['name']
root_type  = traj['root_type']
term_type  = traj['terminal_type']
cell_types = traj['cell_types']

logger.info(f"Trajectory:    {trajectory}")
logger.info(f"Root:          {root_type}")
logger.info(f"Terminal:      {term_type}")

# Validate required columns
for col in ['palantir_pseudotime', 'sample', 'cell_type']:
    if col not in adata.obs.columns:
        raise KeyError(f"Required column '{col}' not found in adata.obs")

if 'counts' not in adata.layers:
    raise KeyError("adata.layers['counts'] not found — required for pseudobulk")

if 'X_umap' not in adata.obsm:
    raise KeyError("adata.obsm['X_umap'] not found — required for QC figure")

# ── 2. Load genotype sample list ──────────────────────────────────────────────

logger.info(f"Loading genotype sample list from: {geno_sample_file}")
with open(geno_sample_file, 'r') as f:
    sample_set = set(f.read().splitlines())

all_samples      = set(adata.obs['sample'].unique())
overlapping      = all_samples & sample_set
missing_from_geno = all_samples - sample_set

logger.info(f"Samples in adata:          {len(all_samples)}")
logger.info(f"Samples in genotype list:  {len(sample_set)}")
logger.info(f"Overlapping samples:       {len(overlapping)}")
logger.info(f"Samples without genotype:  {len(missing_from_geno)}")
if missing_from_geno:
    logger.info(f"Excluded samples: {sorted(missing_from_geno)}")

# ── 3. Restore raw counts ─────────────────────────────────────────────────────
#
#  Replace normalised adata.X with raw integer counts from layers['counts'].
#  Pseudobulk is generated by summing these counts across cells per sample.

logger.info("Restoring raw counts from layers['counts']...")
adata.X = adata.layers['counts'].copy()

# Sanity check — confirm integer values
subset_check = adata.X[:100, :100]
if sp.issparse(subset_check):
    check_vals = subset_check.data
else:
    check_vals = subset_check.flatten()
is_integer = np.all(np.mod(check_vals[check_vals != 0], 1) == 0)
logger.info(f"Raw counts are integers: {is_integer}")
if not is_integer:
    raise ValueError(
        "adata.layers['counts'] does not contain integer values. "
        "Check that raw counts were correctly stored during preprocessing."
    )

# ── 4. Assign quantile bins ───────────────────────────────────────────────────
#
#  For each Q value, assign cells to N equal-cell-number bins based on
#  palantir_pseudotime using pd.qcut. Labels are integers 1 to N.
#  Equal cell numbers (not equal pseudotime intervals) ensures each bin
#  has sufficient cells for pseudobulk aggregation.

logger.info("Assigning pseudotime quantile bins...")
pt = adata.obs['palantir_pseudotime']

for n in Q_VALUES:
    col = f'quantile_Q{n}'
    adata.obs[col] = pd.qcut(
        pt,
        q     = n,
        labels= list(range(1, n + 1))
    ).astype(int)

    bin_counts = adata.obs[col].value_counts().sort_index()
    logger.info(f"\nQ{n} bin cell counts:\n{bin_counts.to_string()}")

    # Log pseudotime boundaries for each bin
    boundaries = pd.qcut(pt, q=n, retbins=True)[1]
    logger.info(f"Q{n} pseudotime boundaries: {np.round(boundaries, 4).tolist()}")

# ── 5. QC Figure ──────────────────────────────────────────────────────────────
#
#  Five-panel UMAP figure plus summary table.
#  All UMAP panels use direct matplotlib scatter to avoid scanpy rendering
#  issues at high cell counts.

logger.info("Generating QC figure...")

palette  = {ct: custom_palette[ct] for ct in cell_types if ct in custom_palette}
umap1    = adata.obsm['X_umap'][:, 0]
umap2    = adata.obsm['X_umap'][:, 1]
pt_vals  = adata.obs['palantir_pseudotime'].values
pt_size  = max(0.2, 20000 / adata.n_obs)

# Quantile colours matching report Panel E scheme
QUANTILE_COLOURS = {
    1: '#e6a023', 2: '#61b6e5', 3: '#efe245',
    4: '#0173b2', 5: '#2aa47e', 6: '#d4632e'
}

def get_bin_colours(n):
    return [QUANTILE_COLOURS.get(i + 1, '#AAAAAA') for i in range(n)]

fig = plt.figure(figsize=(24, 6))
gs  = fig.add_gridspec(1, 5, hspace=0.35, wspace=0.3)

umap_axes = [fig.add_subplot(gs[0, i]) for i in range(5)]

# Panel A — cell type
for ct in adata.obs['cell_type'].cat.categories:
    mask  = adata.obs['cell_type'] == ct
    color = palette.get(ct, '#AAAAAA')
    umap_axes[0].scatter(
        umap1[mask], umap2[mask],
        c=color, s=pt_size, alpha=0.5,
        label=ct, rasterized=True, linewidths=0
    )
umap_axes[0].legend(markerscale=6, fontsize=7, loc='best', framealpha=0.8)
umap_axes[0].set_title('Cell type', fontsize=10)
umap_axes[0].axis('off')

# Panel B — pseudotime
sc_b = umap_axes[1].scatter(
    umap1, umap2, c=pt_vals, cmap='viridis',
    s=pt_size, alpha=0.5, rasterized=True, linewidths=0
)
plt.colorbar(sc_b, ax=umap_axes[1], shrink=0.6, label='Pseudotime')
umap_axes[1].set_title('Palantir pseudotime', fontsize=10)
umap_axes[1].axis('off')

# Panels C-E — Q4, Q5, Q6 bins
for ax_idx, n in enumerate(Q_VALUES):
    col     = f'quantile_Q{n}'
    bins    = adata.obs[col].values
    colours = get_bin_colours(n)
    ax      = umap_axes[ax_idx + 2]

    for b in range(1, n + 1):
        mask = bins == b
        ax.scatter(
            umap1[mask], umap2[mask],
            c=[colours[b - 1]], s=pt_size, alpha=0.5,
            label=f'Q{b}', rasterized=True, linewidths=0
        )
    ax.legend(markerscale=6, fontsize=7, loc='best',
              framealpha=0.8, title=f'Q{n}', title_fontsize=7)
    ax.set_title(f'Q{n} bins', fontsize=10)
    ax.axis('off')

fig.suptitle(
    f'Pseudotime quantile bins: {trajectory}\n'
    f'(n={adata.shape[0]:,} cells)',
    fontsize=12, fontweight='bold', y=1.01
)
fig.savefig(output_figure, dpi=200, bbox_inches='tight')
plt.close(fig)
logger.info(f"QC figure saved: {output_figure}")

# ── 6. Generate pseudobulk CSVs ───────────────────────────────────────────────
#
#  For each Q value and each bin:
#    - Subset adata to cells in that bin
#    - Further subset to genotype-matched samples
#    - Sum raw counts per sample
#    - Validate integer values
#    - Write CSV (samples as rows, genes as columns)
#    - Delete subset and collect garbage
#
#  One CSV per bin per Q value, written to Q{n}/ subdirectory.

summary_rows = []

for n in Q_VALUES:
    col     = f'quantile_Q{n}'
    q_dir   = output_dir / f'Q{n}'
    q_dir.mkdir(parents=True, exist_ok=True)
    logger.info(f"\n── Generating Q{n} pseudobulk ───────────────────────────")

    for b in range(1, n + 1):
        logger.info(f"  Q{n} bin {b}...")

        # Subset to bin
        bin_mask = adata.obs[col] == b
        bin_adata = adata[bin_mask].copy()

        # Filter to genotype-matched samples
        geno_mask  = bin_adata.obs['sample'].isin(sample_set)
        bin_adata  = bin_adata[geno_mask].copy()

        n_cells   = bin_adata.n_obs
        samples   = bin_adata.obs['sample'].unique()
        n_samples = len(samples)
        logger.info(f"    Cells: {n_cells:,} | Samples: {n_samples}")

        if n_samples == 0:
            logger.warning(f"    No genotype-matched samples in Q{n} bin {b} — skipping")
            del bin_adata
            gc.collect()
            continue

        # Generate pseudobulk — sum counts per sample
        pseudobulk_rows = []
        for sample in samples:
            samp_mask   = bin_adata.obs['sample'] == sample
            samp_adata  = bin_adata[samp_mask]
            counts      = samp_adata.X

            if sp.issparse(counts):
                pseudobulk_counts = np.array(counts.sum(axis=0)).flatten()
            else:
                pseudobulk_counts = np.array(counts.sum(axis=0)).flatten()

            pseudobulk_rows.append(pseudobulk_counts)

        pseudobulk_df = pd.DataFrame(
            pseudobulk_rows,
            index   = samples,
            columns = bin_adata.var_names
        )

        # Validate integer values in pseudobulk
        sample_vals = pseudobulk_df.values
        is_integer  = np.all(np.mod(sample_vals[sample_vals != 0], 1) == 0)
        logger.info(f"    Pseudobulk values are integers: {is_integer}")
        if not is_integer:
            raise ValueError(
                f"Non-integer values found in pseudobulk for Q{n} bin {b}. "
                "Check that raw counts were correctly restored into adata.X."
            )

        # Write CSV
        out_csv = str(q_dir / f"Q{n}_bin{b}_{trajectory}_pseudobulk.csv")
        pseudobulk_df.to_csv(out_csv)
        logger.info(f"    Written: {out_csv} ({pseudobulk_df.shape})")

        # Collect summary stats
        cells_per_sample = bin_adata.obs.groupby('sample').size()
        summary_rows.append({
            'trajectory'          : trajectory,
            'quantile_n'          : n,
            'bin'                 : b,
            'n_cells_total'       : n_cells,
            'n_samples'           : n_samples,
            'min_cells_per_sample': int(cells_per_sample.min()),
            'median_cells_per_sample': int(cells_per_sample.median()),
            'max_cells_per_sample': int(cells_per_sample.max()),
            'n_samples_below_10'  : int((cells_per_sample < 10).sum()),
        })

        # Clean up
        del bin_adata, pseudobulk_df, pseudobulk_rows
        gc.collect()

# ── 7. Write summary CSV ──────────────────────────────────────────────────────

logger.info("Writing pseudobulk summary CSV...")
summary_df = pd.DataFrame(summary_rows)
summary_df.to_csv(output_summary, index=False)
logger.info(f"Summary CSV written: {output_summary} ({summary_df.shape})")
logger.info(f"\nPseudobulk summary:\n{summary_df.to_string(index=False)}")

# ── 8. Write sentinel file ────────────────────────────────────────────────────

logger.info("Writing sentinel file...")
with open(sentinel_file, 'w') as f:
    f.write(f"pseudobulk_trajectory completed\n")
    f.write(f"trajectory:  {trajectory}\n")
    f.write(f"timestamp:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write(f"cells:       {adata.shape[0]:,}\n")
    f.write(f"samples:     {len(overlapping)}\n")
    f.write(f"Q values:    {Q_VALUES}\n")

logger.info(f"Sentinel written: {sentinel_file}")
logger.info("Done.")
