MERGE_FQ_JSON: ../config/samples_plate1_subset.json
plate:
  - plate1
  - plate2

root_dir: /scratch/c.c1477909/eQTL_study_2025/

cell_types: 
  - "ExN-1"
#  - "ExN-2"
#  - "InN"
#  - "OPC"
#  - "RG"
#  - "Endo-Peri"
#  - "MG"

scanpy:
  qc:
    input: 
      plate: ../results/02PARSE/combine_{plate}/all-sample/DGE_filtered/anndata.h5ad
      nb: scripts/scanpy_qc.ipynb  
    output: ../results/03SCANPY/scanpy_qc_{plate}.html
    nb_out: ../results/03SCANPY/scanpy_qc_{plate}_pm.ipynb
    html_out: scanpy_qc_{plate}.html
    log: ../results/00LOG/03SCANPY/scanpy_qc_{plate}.log

  clustering:
    input: scripts/scanpy_clustering.ipynb
    output: ../results/03SCANPY/scanpy_clustering.html 
    nb_out: ../results/03SCANPY/scanpy_clustering_pm.ipynb
    html_out: scanpy_clustering.html
    log: ../results/00LOG/03SCANPY/scanpy_clustering.log

  annotation:
    input: scripts/scanpy_annotation.ipynb
    output: ../results/03SCANPY/scanpy_annotation.html
    nb_out: ../results/03SCANPY/scanpy_annotation_pm.ipynb
    html_out: scanpy_annotation.html
    log: ../results/00LOG/03SCANPY/scanpy_annotation.log

  pseudobulk:
    input: scripts/scanpy_cell_label_and_pseudobulk.ipynb
    output: ../results/03SCANPY/scanpy_cell_label_and_pseudobulk.html
    nb_out: ../results/03SCANPY/scanpy_cell_label_and_pseudobulk_pm.ipynb
    html_out: scanpy_cell_label_and_pseudobulk.html
    log: ../results/00LOG/03SCANPY/scanpy_cell_label_and_pseudobulk.log

  extra:
    input: scripts/scanpy_extra.ipynb
    output: ../results/03SCANPY/scanpy_extra.html
    nb_out: ../results/03SCANPY/scanpy_extra_pm.ipynb
    html_out: scanpy_extra.html
    log: ../results/00LOG/03SCANPY/scanpy_extra.log

  env: "../envs/eqtl_study.yml"

eQTL:
  tool: tensorqtl
  num_chunks: 100
  perm_min: 1000
  perm_max: 10000
  plink_prefix: ../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt
  out_prefix: ../results/04TENSORQTL/chrALL_final.filt
  window: 500000
input_files:
  counts: ../results/03SCANPY/pseudobulk/{cell_type}_tmm.bed
  genotypes: ../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt.vcf.gz
  covariates: ../results/03SCANPY/pseudobulk/{cell_type}_covariates.txt
output_files:
  counts_gz: ../results/03SCANPY/pseudobulk/{cell_type}_tmm.bed.gz
  genotypes_plink: ../results/04TENSORQTL/chrALL_final.filt.pgen 
  fastqtl_output: ../results/04FASTQTL/{cell_type}_nom_{chunk}_txt.gz
  fastqtl_perm_output: ../results/04FASTQTL/{cell_type}_perm_{chunk}_txt.gz
  tensorqtl_out_prefix: ../results/04TENSORQTL/{cell_type}/{cell_type}_nom
  tensorqtl_output: ../results/04TENSORQTL/{cell_type}/{cell_type}_nom.cis_qtl_pairs.4.parquet
  tensorqtl_perm_out_prefix: ../results/04TENSORQTL/{cell_type}/{cell_type}_perm
  tensorqtl_perm_output: ../results/04TENSORQTL/{cell_type}/{cell_type}_perm.cis_qtl.txt.gz
  tensorqtl_perm_log: ../results/04TENSORQTL/{cell_type}/{cell_type}_perm.tensorQTL.cis.log
  tensorqtl_tss_plt: ../results/figs/tss_density_plot_combined.png
  tensorqtl_tss_tbl: ../results/tables/tensorqtl_summary_table.tsv

log_files:
  fastqtl_zip: ../results/00LOG/04FASTQTL/{cell_type}_bgzip.log
  fastqtl: ../results/00LOG/04FASTQTL/{cell_type}_nom_{chunk}.log
  fastqtl_perm: ../results/00LOG/04FASTQTL/{cell_type}_perm_{chunk}.log
  tensorqtl: ../results/00LOG/04TENSORQTL/{cell_type}_nom.log
  tensorqtl_perm: ../results/00LOG/04TENSORQTL/{cell_type}_perm.log
  tensorqtl_tss: ../results/00LOG/04TENSORQTL/tss.log   

containers:
  fastqtl: ../resources/containers/gtex_eqtl.sif
  tensorqtl: ../resources/containers/tensorqtl.sif
  genotype-qc2hrc: ../resources/containers/genotype-qc2hrc_latest.sif 
  R: ../resources/containers/seurat5f.sif  


slsdr:
  get_sig_eGenes:
    output: ../results/05SLDSR/eGenes_fdr_0.05/{cell_type}/{cell_type}_eGenes_fdr_0.05.tsv
    log: ../results/00LOG/05SLDSR/get_sig_eGenes_{cell_type}.log
  prep_susie_input:
    output: ../results/05SLDSR/eGenes_for_SuSiE/{cell_type}/{cell_type}_prep_susie_input.done
    log: ../results/00LOG/05SLDSR/prep_susie_input_{cell_type}.log

plot_qtl:
  run: True  
  pairs_file: ../results/04TENSORQTL/plots/snp_gene_pairs.csv
  out_dir: ../results/04TENSORQTL/plots
  out_file: ../results/04TENSORQTL/plots/plot_qtl.done
  expression_dir: ../results/03SCANPY/pseudobulk
  log: ../results/00LOG/04TENSORQTL/plot_qtl.log 

geno_pre_impute:
  convert_raw:
    input:
      ped: ../resources/genotypes/PLINK_040325_1121_Bray_hg19/Bray_hg19.ped 
      map: ../resources/genotypes/PLINK_040325_1121_Bray_hg19/Bray_hg19.map
    output: ../results/04GENOTYPES/GenotypeQCtoHRC/eqtl_genotypes_hg19.bed
    in_prefix: ../resources/genotypes/PLINK_040325_1121_Bray_hg19/Bray_hg19
    out_prefix: ../results/04GENOTYPES/GenotypeQCtoHRC/eqtl_genotypes_hg19
    log: ../results/00LOG/04GENOTYPES/GenotypeQCtoHRC/convert_raw.log
  
  make_kgp3_pgen:
    input: ../results/04GENOTYPES/GenotypeQCtoHRC/dragondata_extra/ancestry_reference/1kgp/kgp3.array_snps.id
    output: ../results/04GENOTYPES/GenotypeQCtoHRC/dragondata_extra/ancestry_reference/1kgp/kgp3.array_snps.pgen  
    log: ../results/00LOG/04GENOTYPES/GenotypeQCtoHRC/make_kgp3_pgen.log
    workdir: ../results/04GENOTYPES/GenotypeQCtoHRC/dragondata_extra/ancestry_reference/1kgp/    

  genotype-qc2hrc:
    output: ../results/04GENOTYPES/GenotypeQCtoHRC/eqtlgenotypeshg38pretm.qc_report.html
    in_prefix: eqtl_genotypes_hg19
    out_prefix: eqtl_genotypes_hg38_preTM
    shortname: eqtlhg38tm
    log: ../results/00LOG/04GENOTYPES/GenotypeQCtoHRC/genotype-qc2hrc.log
    
    
genotypes:
  impute_check:
    input:  ../results/04GENOTYPES/TOPMED/chr_{chr}.zip
    output: 
      tsv: ../results/04GENOTYPES/TOPMED/impute_check/chr_{chr}_summary.tsv
      vcf: ../results/04GENOTYPES/TOPMED/chr{chr}.dose.vcf.gz
    params: 
      dir: ../results/04GENOTYPES/TOPMED/
      pwd: ../config/passwords/topmed.txt 
    log: ../results/00LOG/04GENOTYPES/TOPMED/impute_check_{chr}.log
  impute_check_cat:
    output: ../results/04GENOTYPES/TOPMED/impute_check/chr_ALL_summary.tsv
  dwnld_dbsnp_ref:
    output: ../resources/refs/dbSNP/dbsnp_hg38_build156.vcf.gz.tbi 
    params:
      web_link: https://ftp.ncbi.nih.gov/snp/redesign/latest_release/VCF/GCF_000001405.40.gz
      prefix: ../resources/refs/dbSNP/dbsnp_hg38_build156.vcf.gz 
    log: ../results/00LOG/04GENOTYPES/TOPMED/dwnld_dbsnp_ref.log
  add_rsID:
    output: ../results/04GENOTYPES/TOPMED/dbSNP_annotated/chr{chr}.dbSNP.vcf.gz
    log: ../results/00LOG/04GENOTYPES/TOPMED/add_rsID_{chr}.log     
  vcf_cat:
    output: ../results/04GENOTYPES/TOPMED/dbSNP_annotated/chrALL.dbSNP.vcf.gz
    log: ../results/00LOG/04GENOTYPES/TOPMED/vcf_cat.log    
  filter_tags:
    output: ../results/04GENOTYPES/TOPMED/filtered/chrALL.filt.vcf.gz
    params:
      hwe: 0.0001
      maf: 0.05
      rsq: 0.8  
    log: ../results/00LOG/04GENOTYPES/TOPMED/filter_tags.log    
  check_VCF:  
    input:
      ref_gz: ../resources/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
    output: 
      log: ../results/04GENOTYPES/TOPMED/filtered/check_vcf.check.log
      list: ../results/04GENOTYPES/TOPMED/filtered/exclusion_list.txt
      ref: ../resources/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
      fai: ../resources/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai
    params: ../results/04GENOTYPES/TOPMED/filtered/check_vcf
    log: ../results/00LOG/04GENOTYPES/TOPMED/check_VCF.log
  exclude_SNPs:
    output: ../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt.vcf.gz
    log: ../results/00LOG/04GENOTYPES/TOPMED/exclde_SNPs.log
  idx_vcf:
    output: ../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt.vcf.gz.tbi
    log: ../results/00LOG/04GENOTYPES/TOPMED/idx_vcf.log
  create_combined_log:
    output: ../results/04GENOTYPES/TOPMED/filtered/combined_genotype_processing.log
    log: ../results/00LOG/04GENOTYPES/TOPMED/create_combined_log.log 
  get_sample_list:
    output: ../results/04GENOTYPES/TOPMED/filtered/geno_sample_list.txt
  vcf_to_plink:
    output: ../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt.bed
    params: ../results/04GENOTYPES/TOPMED/filtered/chrALL_final.filt
    log: ../results/00LOG/04GENOTYPES/TOPMED/vcf_to_plink.log
  get_ld_pruned_snps:
    output: ../results/04GENOTYPES/TOPMED/covariates/ld_prune.prune.in
    params: ../results/04GENOTYPES/TOPMED/covariates/ld_prune
    log: ../results/00LOG/04GENOTYPES/TOPMED/get_ld_pruned_snps.log
  prune_genotypes:
    output: ../results/04GENOTYPES/TOPMED/covariates/chrALL_final.filt.ld_pruned.bed
    params: ../results/04GENOTYPES/TOPMED/covariates/chrALL_final.filt.ld_pruned
    log: ../results/00LOG/04GENOTYPES/TOPMED/prune_genotypes.log
  calc_genotype_pcs:
    output: ../results/04GENOTYPES/TOPMED/covariates/pca.eigenvec
    params: ../results/04GENOTYPES/TOPMED/covariates/pca
    pcs: 10
    log: ../results/00LOG/04GENOTYPES/TOPMED/calc_genotype_pcs.log
